# Generated by Django 5.0.7 on 2025-02-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossvolapp', '0002_event_eventenrollment_eventskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChat',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='ossvolapp.event')),
            ],
            options={
                'db_table': 'event_chat',
            },
        ),
        migrations.CreateModel(
            name='EventChatHistory',
            fields=[
                ('chat_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='ossvolapp.eventchat')),
                ('from_org_id', models.ForeignKey(blank=True, db_column='from_org_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_chat_logs', to='ossvolapp.profilesorg')),
                ('from_vol_id', models.ForeignKey(blank=True, db_column='from_vol_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_chat_logs', to='ossvolapp.profilesvolunteer')),
            ],
            options={
                'db_table': 'event_chat_history',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recommendation_msg', models.CharField(blank=True, max_length=200, null=True)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ossvolapp.event')),
                ('from_org_id', models.ForeignKey(blank=True, db_column='from_org_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_recommendations', to='ossvolapp.profilesorg')),
                ('from_vol_id', models.ForeignKey(blank=True, db_column='from_vol_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_sent_recommendations', to='ossvolapp.profilesvolunteer')),
                ('to_vol_id', models.ForeignKey(db_column='to_vol_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations', to='ossvolapp.profilesvolunteer')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
    ]
